apiVersion: nginxcrd.k8s.io/v1
kind: Nginxconf
metadata:
      name: www.demo.com.conf
spec:
      conf: |
           upstream demo_server {
                server 192.168.100.23:8080
           }
           server {
                listen 80;
                server_name    www.demo.com;
                location / {
                    proxy_pass http://demo_server;
                }
           }

