/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	nginxcrdv1 "github.com/cstoppgmr/nginxcrd-custom-resource/pkg/apis/nginxcrd/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNginxconves implements NginxconfInterface
type FakeNginxconves struct {
	Fake *FakeNginxcrdV1
	ns   string
}

var nginxconvesResource = schema.GroupVersionResource{Group: "nginxcrd.k8s.io", Version: "v1", Resource: "nginxconves"}

var nginxconvesKind = schema.GroupVersionKind{Group: "nginxcrd.k8s.io", Version: "v1", Kind: "Nginxconf"}

// Get takes name of the nginxconf, and returns the corresponding nginxconf object, and an error if there is any.
func (c *FakeNginxconves) Get(ctx context.Context, name string, options v1.GetOptions) (result *nginxcrdv1.Nginxconf, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nginxconvesResource, c.ns, name), &nginxcrdv1.Nginxconf{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nginxcrdv1.Nginxconf), err
}

// List takes label and field selectors, and returns the list of Nginxconves that match those selectors.
func (c *FakeNginxconves) List(ctx context.Context, opts v1.ListOptions) (result *nginxcrdv1.NginxconfList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nginxconvesResource, nginxconvesKind, c.ns, opts), &nginxcrdv1.NginxconfList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &nginxcrdv1.NginxconfList{ListMeta: obj.(*nginxcrdv1.NginxconfList).ListMeta}
	for _, item := range obj.(*nginxcrdv1.NginxconfList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nginxconves.
func (c *FakeNginxconves) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nginxconvesResource, c.ns, opts))

}

// Create takes the representation of a nginxconf and creates it.  Returns the server's representation of the nginxconf, and an error, if there is any.
func (c *FakeNginxconves) Create(ctx context.Context, nginxconf *nginxcrdv1.Nginxconf, opts v1.CreateOptions) (result *nginxcrdv1.Nginxconf, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nginxconvesResource, c.ns, nginxconf), &nginxcrdv1.Nginxconf{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nginxcrdv1.Nginxconf), err
}

// Update takes the representation of a nginxconf and updates it. Returns the server's representation of the nginxconf, and an error, if there is any.
func (c *FakeNginxconves) Update(ctx context.Context, nginxconf *nginxcrdv1.Nginxconf, opts v1.UpdateOptions) (result *nginxcrdv1.Nginxconf, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nginxconvesResource, c.ns, nginxconf), &nginxcrdv1.Nginxconf{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nginxcrdv1.Nginxconf), err
}

// Delete takes name of the nginxconf and deletes it. Returns an error if one occurs.
func (c *FakeNginxconves) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nginxconvesResource, c.ns, name), &nginxcrdv1.Nginxconf{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNginxconves) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nginxconvesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &nginxcrdv1.NginxconfList{})
	return err
}

// Patch applies the patch and returns the patched nginxconf.
func (c *FakeNginxconves) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *nginxcrdv1.Nginxconf, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nginxconvesResource, c.ns, name, pt, data, subresources...), &nginxcrdv1.Nginxconf{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nginxcrdv1.Nginxconf), err
}
